### ISSUE TITLE
Antwoorden 3.10.2

### ISSUE THREAD

**Issue by AnnePommee** [UtrechtUniversity/KI1V13001-Inleiding-Logica#11]
De antwoorden van c en d van 3.10.2 staan niet in de notes bij de uitwerkingen. Ik weet niet of daar een reden voor is of dat ik ze gewoon niet kan vinden... Het zou tof zijn als die erbij komen, zodat ik daar nog mee kan oefenen.

Edit: Oh ik zie nu dat er heel veel uitwerkingen niet in staan. Hoezo is dat? Maakt oefenen een stuk lastiger als je het niet kan checken...

**Comment by jkorb** [comment]
Thanks @AnnePommee ! Helaas is het nog niet gelukt om alle opdrachten op te lossen, maar we werken hieran. In de tussentijd kun je je SA om feedback vragen.
