### ISSUE TITLE
10.4.3 typo?

### ISSUE THREAD

**Issue by rfigge24** [UtrechtUniversity/KI1V13001-Inleiding-Logica#20]
onder het voorbeeld staat het Model dat hoort bij de Branch. Hier staat dat dat q(in het model bij de branch) = [**p**]~B = {q}. moet dit niet zijn: q(in het model bij de branch) = [**q**]~B = {q}?
anders gezecht moet de p waar de pijl naar wijst in de screenshot niet een q zijn?
![image](https://user-images.githubusercontent.com/91072139/138752073-390a1253-66b2-4467-8cca-84ac163e771b.png)

**Comment by jkorb** [comment]
Thanks @rfigge24 . A bit late, but will fix :)
