### ISSUE TITLE
Typo uitwerking 2.7.5

### ISSUE THREAD

**Issue by JuliaBartelink** [UtrechtUniversity/KI1V13001-Inleiding-Logica#22]
In de uitwerking van 2.7.5 staat als conclusie "So, we can conclude that every prime bigger than two is even". Dit zou "odd" moeten zijn en niet "even", omdat de vraag was om te bewijzen dat elk priemgetal groter dan twee oneven is.

**Comment by jkorb** [comment]
Klopt! Thanks @caprisun05 , ga ik verbeteren.
