### ISSUE TITLE
Chapter 3, 3.4.5 should say don't

### ISSUE THREAD

**Issue by Juliekenney** [UtrechtUniversity/KI1V13001-Inleiding-Logica#26]
hi Johannes,
In 3.4.5 (in the notes on p. 47) after the definition of X\Y, it says that if X and Y overlap, that the intersection of X and Y is equivalent to an empty set. Which (I think) should be; If X and Y don't overlap, the intersection of X and Y is equivalent to an empty set. 
:)

**Comment by jkorb** [comment]
Hi @Juliekenney ! So, I think you're referring to the following sentence:

![gh-sentence](https://user-images.githubusercontent.com/56480857/192260737-01371a37-e927-4396-8282-1ea1faaeb438.png)

Right? In that case, the sentence seems correct to me. If X and Y overlap, then their interection is _not_ the empty set. In other words, if X and Y overlap, then there elements in the intersection of X and Y. Or am I missing something? In the example that follows, for example, the intersection of {1,2,3,4} and {2,4,6} is non-empty and, in fact, {2,4}. 

I'll close the issue with this comment, but please feel free to re-open it if I misunderstood anything!
