### ISSUE TITLE
Unclear question 9.7.1

### ISSUE THREAD

**Issue by teuncb** [UtrechtUniversity/KI1V13001-Inleiding-Logica#34]
![image](https://user-images.githubusercontent.com/50371179/196940201-a4cc9afd-55da-4a2d-8b8e-1ddc4a76fdf8.png)

9.7.1 asks you to use the "models" from (9.2.2.i.d), but (d) is only one model.

**Comment by jkorb** [comment]
Thanks @teuncb ! Yes, it should be "model". Will fix :)
