### ISSUE TITLE
Slide 67 lecture 3: mistake in items in set {Robbie, 0}

### ISSUE THREAD

**Issue by RoosScheffers** [UtrechtUniversity/KI1V13001-Inleiding-Logica#8]
The slide says: {1, a, {Robbie; 0}} contains 1, a, 0, and the set (!) {Robbie} 

This should be: {1, a, {Robbie; 0}} contains 1, a, and the set (!) {Robbie, 0}

**Comment by jkorb** [comment]
Yes, you're very right!
